### ISSUE TITLE
compilation does not works if to compile this folder(file from this folder) into subfolder

### ISSUE THREAD

**Issue by dzmitry-lahoda** [fluencelabs/aqua-playground#6]
no error is given either (ubuntu 20)

**Comment by folex** [comment]
@dzmitry-lahoda can you please provide directory layout to reproduce the problem? List of `mkdir`s, `ls -l`, and then how you run aqua-cli would suffice

**Comment by dzmitry-lahoda** [comment]
may be i missed something, tried possible scenarios - works.
